-- MySQL Script generated by MySQL Workbench
-- Sat May 16 19:41:43 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `ID_cliente` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(35) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamentos` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `ubicacion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operadores` (
  `id_operador` INT NOT NULL AUTO_INCREMENT,
  `correo_operador` VARCHAR(35) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_operador`),
  INDEX `id_departamento` (`id_departamento` ASC) VISIBLE,
  UNIQUE INDEX `correo_operador_UNIQUE` (`correo_operador` ASC) VISIBLE,
  CONSTRAINT `operador_ibfk_1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`departamentos` (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `ID_ticket` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_cierre` DATETIME NULL DEFAULT NULL,
  `categoria` ENUM('Hardware', 'Software', 'Redes', 'Seguridad') NOT NULL,
  `prioridad` ENUM('Baja', 'Media', 'Alta', 'Critica') NOT NULL,
  `estado` ENUM('Abierto', 'En Proceso', 'Cerrado', 'Archivado') NOT NULL,
  `cliente` INT NOT NULL,
  `operador` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ticket`),
  INDEX `correo_cliente` (`cliente` ASC) VISIBLE,
  INDEX `correo_operador` (`operador` ASC) VISIBLE,
  CONSTRAINT `ticket_ibfk_1`
    FOREIGN KEY (`cliente`)
    REFERENCES `mydb`.`clientes` (`ID_cliente`),
  CONSTRAINT `ticket_ibfk_2`
    FOREIGN KEY (`operador`)
    REFERENCES `mydb`.`operadores` (`id_operador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mensaje` (
  `ID_mensaje` INT NOT NULL AUTO_INCREMENT,
  `ID_ticket` INT NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `remitente` ENUM("cliente", "operador") NOT NULL,
  PRIMARY KEY (`ID_mensaje`),
  INDEX `ID_ticket` (`ID_ticket` ASC) VISIBLE,
  CONSTRAINT `mensaje_ibfk_1`
    FOREIGN KEY (`ID_ticket`)
    REFERENCES `mydb`.`ticket` (`ID_ticket`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
