-- MySQL Script generated by MySQL Workbench
-- Fri May 15 12:50:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `correo` VARCHAR(35) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`correo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamentos` (
  `id_departamento` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `ubicacion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operador` (
  `correo_operador` VARCHAR(35) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `id_departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`correo_operador`),
  INDEX `id_departamento` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `operador_ibfk_1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`departamentos` (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `ID_ticket` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_cierre` DATETIME NULL DEFAULT NULL,
  `categoria` ENUM('Hardware', 'Software', 'Redes', 'Seguridad') NOT NULL,
  `prioridad` ENUM('Baja', 'Media', 'Alta', 'Critica') NOT NULL,
  `estado` ENUM('Abierto', 'En Proceso', 'Cerrado', 'Archivado') NOT NULL,
  `correo_cliente` VARCHAR(35) NOT NULL,
  `correo_operador` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ticket`),
  INDEX `correo_cliente` (`correo_cliente` ASC) VISIBLE,
  INDEX `correo_operador` (`correo_operador` ASC) VISIBLE,
  CONSTRAINT `ticket_ibfk_1`
    FOREIGN KEY (`correo_cliente`)
    REFERENCES `mydb`.`clientes` (`correo`),
  CONSTRAINT `ticket_ibfk_2`
    FOREIGN KEY (`correo_operador`)
    REFERENCES `mydb`.`operador` (`correo_operador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mensaje` (
  `ID_mensaje` INT NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `ID_ticket` INT NOT NULL,
  `correo_cliente` VARCHAR(35) NULL DEFAULT NULL,
  `correo_operador` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_mensaje`),
  INDEX `ID_ticket` (`ID_ticket` ASC) VISIBLE,
  INDEX `correo_cliente` (`correo_cliente` ASC) VISIBLE,
  INDEX `correo_operador` (`correo_operador` ASC) VISIBLE,
  CONSTRAINT `mensaje_ibfk_1`
    FOREIGN KEY (`ID_ticket`)
    REFERENCES `mydb`.`ticket` (`ID_ticket`),
  CONSTRAINT `mensaje_ibfk_2`
    FOREIGN KEY (`correo_cliente`)
    REFERENCES `mydb`.`clientes` (`correo`),
  CONSTRAINT `mensaje_ibfk_3`
    FOREIGN KEY (`correo_operador`)
    REFERENCES `mydb`.`operador` (`correo_operador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
